### ISSUE TITLE
Nothing shows on Explorer page 

### ISSUE THREAD

**Issue by ibrahimuslu** [ismailarilik/visual-python#7]
No error on terminal window and no errors but nothing shows on window areas are empty
Is that a problem or is it because of its in development

![image](https://user-images.githubusercontent.com/146313/60397025-1cd6b480-9b51-11e9-99d4-6691cbff0478.png)

**Comment by ismailarilik** [comment]
It should work. You should open a folder by Ctrl+Shift+O keys or via the menu button in File menu.

**Comment by ibrahimuslu** [comment]
Yes its ok now. 
I got it working. 
Thanks for your patience. 

Its very valuable work.
